# : Manager [[[

[mgr]
cwd = { fg = "#e5e1e9" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff72a8", bg = "#ff72a8" }
marker_cut      = { fg = "#ffd8e7", bg = "#ffd8e7" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ecb8ce", bg = "#ecb8ce" }

# Count
count_copied   = { fg = "#301121", bg = "#ffd8e7" }
count_cut      = { fg = "#301121", bg = "#ffd8e7" }
count_selected = { fg = "#2f295f", bg = "#ecb8ce" }

# Border
border_symbol = "│"
border_style  = { fg = "#c7bfff" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#c7bfff", bold = true, bg = "#141318" }
inactive  = { fg = "#c8c3dc", bg = "#141318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#c7bfff", fg = "#2f295f", bold = true }
normal_alt  = { bg = "#47464f", fg = "#c9c5d0" }

# Select mode
select_main = { bg = "#c8c3dc", fg = "#312e41", bold = true }
select_alt  = { bg = "#47464f", fg = "#c9c5d0" }

# Unset mode
unset_main = { bg = "#ecb8ce", fg = "#482537", bold = true }
unset_alt  = { bg = "#47464f", fg = "#c9c5d0" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#6f62a4" }
perm_write = { fg = "#cc3f7b" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff3f89" }
perm_sep   = { fg = "#6346ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#c7bfff", bg = "#3a383e" }
progress_error  = { fg = "#ffb4ab", bg = "#3a383e" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a383e" }
cand = { fg = "#c7bfff" }
rest = { fg = "#2f295f" }
desc = { fg = "#e5e1e9" }
separator = " ▶ "
separator_style = { fg = "#e5e1e9" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#ecb8ce" }
title_warn  = { fg = "#c7bfff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#c7bfff" }
active = { fg = "#ecb8ce", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c7bfff" }
value  = { fg = "#e5e1e9" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#c7bfff", bg = "#2f295f" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#c7bfff" }
title   = {}
hovered = { fg = "#ffd8e7", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e5e1e9" }
run    = { fg = "#e5e1e9" }
footer = { fg = "#312e41", bg = "#c8c3dc" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e5e1e9" },
    { url = "*/", fg = "#c7bfff" },
]

# : ]]]
