cursor            #c7bfff
cursor_text_color #2f295f

foreground            #e5e1e9
background            #0e0e13
selection_foreground  #312e41
selection_background  #c8c3dc
url_color             #c8c3dc

#: black 000000 767676
color0  #141318
color8  #35343a
#: red cc0403 f2201f
color1  #ba7575
color9  #eddbdb
#: green 19cb00 23fd00
color2  #c8c3dc
color10 #e5dff9
#: yellow cecb00 fffd00
color3  #ecb8ce
color11 #ffd8e7
#: blue 0d73cc 1a8fff
color4  #463f77
color12 #c7bfff
#: magenta cb1ed1 fd28ff
color5  #474459
color13 #c8c3dc
#: cyan 0dcdcd 14ffff
color6  #613b4d
color14 #ecb8ce
#: white dddddd ffffff
color7  #c9c5d0
color15 #e5e1e9

mark1_foreground #1a1249
mark1_background #e4dfff
mark2_foreground #1b192c
mark2_background #e5dff9
mark3_foreground #301121
mark3_background #ffd8e7

active_tab_foreground #2f295f
active_tab_background #c7bfff
inactive_tab_foreground #e4dfff
inactive_tab_background #463f77

active_border_color #c7bfff
inactive_border_color #2f295f
# bell_border_color #ff5a00
